---
- name: install_ngnix
  hosts: demo
  gather_facts: false
  become: true
  tasks:
    - name: Add epel-release repo
      yum:
        name: "epel-release"
        state: "present"
    - name: Install nginx
      yum:
        name: "nginx"
        state: "present"
    - name: Insert Index Page
      copy:
        src: "index.html"
        dest: "/usr/share/nginx/html/index.html"
    - name: Copy config file
      copy:
        src: "nginx.conf"
        dest: "/etc/nginx/nginx.conf"
    - name: Copy Certificates
      copy:
        src: "{{ item }}"
        dest: "/etc/pki/nginx/"
      with_fileglob:
        - "demo*"
    - name: Ngnix Config test
      command: nginx -t -c /etc/nginx/nginx.conf
      register: config_test_out
    - name: Check Nginx config test result
      assert:
        that:
          - "'syntax is ok' not in config_test_out"
          - "'test is successful' not in config_test_out"
        fail_msg: "Issue with ngnix conf file. Failed configtest. Please correct and rerun"
        success_msg: "Ngnix config test passed !!"
    - name: Start NGiNX
      service:
        name: "nginx"
        state: "started"
